source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'
# gem "thin", "~> 1.5.0"

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem "haml", "~> 4.0.2"
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

group :development, :test do
  gem 'sqlite3'

  gem "turn", "~> 0.8.2", :require => false
  gem "cucumber", "~> 1.2.1"
  gem "rspec", "~> 2.13.0"
  gem "rspec-rails", "~> 2.13.2"
  gem "machinist", "~> 2.0.0.beta2"
  gem 'faker', '~> 1.1.2'

  gem 'haml-rails', '~> 0.4'
  gem 'zeus', '~> 0.13.3'
  gem 'jasmine', '~> 1.3.2'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
